### ISSUE TITLE
Distributed Version

### ISSUE THREAD

**Issue by silvered-shark** [Sachinluthra/mysampletask#1]
Is there any distributed version of TensorFlow that could work on multiple machines?

**Comment by scarlett1130** [comment]
Thanks for the question! To reiterate what I said https://github.com/tensorflow/tensorflow/issues/12#issuecomment-155150681, we are working on making a distributed implementation available, it's currently not in the initial release. Please stay tuned, and take a look at the cifar multi-gpu tutorial for a flavor of how we handle multiple 'devices': http://tensorflow.org/tutorials/deep_cnn/index.md
